# Generated by Django 4.0.6 on 2024-04-25 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localizacao',
            old_name='festival',
            new_name='Festival',
        ),
    ]
