# Generated by Django 4.0.6 on 2024-04-24 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='area_cientifica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areasCientificas', to='curso.areacientifica'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='curso.disciplina'),
        ),
    ]
