# Generated by Django 4.0.6 on 2024-05-03 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_alter_disciplina_area_cientifica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='area_cientifica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='curso.areacientifica'),
        ),
    ]
