# Generated by Django 4.0.6 on 2024-04-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0004_alter_album_banda_alter_banda_foto_banda_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='capa',
        ),
        migrations.AddField(
            model_name='album',
            name='foto_Album',
            field=models.ImageField(blank=True, null=True, upload_to='bandas/fotos'),
        ),
        migrations.AlterField(
            model_name='banda',
            name='foto_banda',
            field=models.ImageField(blank=True, null=True, upload_to='bandas/fotos'),
        ),
    ]
