# Generated by Django 4.0.6 on 2024-05-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0005_remove_album_capa_album_foto_album_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='biografia',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='musica',
            name='letra',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
